name:                Data-Structures
version:             0.1.0.0
github:              "psygo/Data-Structures"
license:             BSD3
author:              "Philippe Fanaro"
maintainer:          "philippefanaro@gmail.com"
copyright:           "GPL-3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/psygo/Data-Structures#readme>

dependencies:
- base >= 4.7 && < 5
- pretty-simple >= 3.0

library:
  source-dirs: src

executables:
  Data-Structures-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Data-Structures
    when:
    - condition: false
      other-modules: Paths_pkg

tests:
  Data-Structures-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Data-Structures
    when:
    - condition: false
      other-modules: Paths_pkg
